DROP TABLE PLAYLIST_DETAIL;    --1
DROP TABLE PAYMENT_DETAIL;     --2
DROP TABLE FRIEND_LIST;  --3
DROP TABLE CART;  --4
DROP TABLE RECOMMEND_LIST;  --5
DROP TABLE BOARD_COMMENT; --6
DROP TABLE BOARD; --7
DROP TABLE PLAYLIST; --8
DROP TABLE RECENT_MUSIC;  --9
DROP TABLE MUSIC_COMMENT; -- 10
DROP TABLE MUSIC_FILE; --11
DROP TABLE MUSIC_LIST; --12
DROP TABLE MEMBER; --13
DROP TABLE LOCATION;   --14 
------------
CREATE TABLE LOCATION
     (
       LOCATION_NO NUMBER PRIMARY KEY
     , LOCATION_NAME VARCHAR2(20) NOT NULL
     );
     
CREATE TABLE MEMBER 
     ( 
	   MEMBER_NO NUMBER PRIMARY KEY      
     , LOCATION_NO NUMBER REFERENCES LOCATION                  
     , MEMBER_ID VARCHAR2(20) NOT NULL            
     , MEMBER_PWD VARCHAR2(20) NOT NULL           
     , MEMBER_NAME VARCHAR2(30) NULL              
     , EMAIL VARCHAR2(30) NOT NULL                
     , GENDER CHAR(1) NOT NULL                    
     , AGE NUMBER NOT NULL                        
     , STATUS CHAR(1) DEFAULT 'Y' NOT NULL        
     , ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL  
     , REPORT_COUNT NUMBER NULL                   
     );           

           CREATE TABLE MUSIC_LIST 
    (
      MUSIC_NO      NUMBER         NOT NULL
    , MUSIC_TITLE   VARCHAR2(30)   NOT NULL
    , MUSIC_SINGER  VARCHAR2(30)   NOT NULL 
    , MUSIC_COUNT   NUMBER         NOT NULL 
    , MUSIC_GENRE   VARCHAR2(20)   NOT NULL
    , MUSIC_LIKE    NUMBER         NULL 
    , MUSIC_DISLIKE NUMBER         NULL 
    , LYRICS        VARCHAR2(4000) NULL 
    , MUSIC_PUBLIC_STATUS  CHAR(1)        DEFAULT 'Y' NOT NULL
    , CONSTRAINT PK_MUSIC_LIST PRIMARY KEY (MUSIC_NO)
    );

CREATE TABLE MUSIC_FILE 
    (
      MUSIC_NO NUMBER NOT NULL                 
    , MUSIC_FILE_ORIGIN_NAME VARCHAR2(30) NOT NULL 
    , MUSIC_FILE_EDIT_NAME VARCHAR2(30) NOT NULL  
    , MUSIC_FILE_STORE_PATH VARCHAR2(30) NOT NULL 
    , MUSIC_IMAGE_ORIGIN_NAME VARCHAR2(30)       
    , MUSIC_IMAGE_EDIT_NAME VARCHAR2(30)        
    , MUSIC_IMAGE_PATH VARCHAR2(30)              
    , CONSTRAINT PK_MUSIC_FILE PRIMARY KEY (MUSIC_NO) 
    );
    
    
    CREATE TABLE MUSIC_COMMENT 
    (
      MUSIC_COMMENT_NO NUMBER PRIMARY KEY  
    , MUSIC_NO NUMBER NOT NULL             
    , MEMBER_NO NUMBER NOT NULL            
    , COMMENT_TEXT VARCHAR2(600 CHAR) NOT NULL 
    , COMMENT_LIKE NUMBER                  
    , COMMENT_DISLIKE NUMBER              
    , COMMENT_DATE DATE                     
    );
    
     CREATE TABLE 
 RECENT_MUSIC
            (
              MEMBER_NO NUMBER NOT NULL
            , MUSIC_NO NUMBER NOT NULL
            
            , CONSTRAINT FK_RECENT_MUSIC_MEMBER_NO FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
            , CONSTRAINT FK_RECENT_MUSIC_MUSIC_NO FOREIGN KEY (MUSIC_NO) REFERENCES MUSIC_FILE(MUSIC_NO)
);


CREATE TABLE
    PLAYLIST
           (
             PLAYLIST_NO NUMBER CONSTRAINT PK_PLAYLIST_NO PRIMARY KEY
           , MEMBER_NO NUMBER CONSTRAINT FK_PLAYLIST_MEMBER_NO REFERENCES MEMBER(MEMBER_NO) NOT NULL
           , PLAYLIST_NAME VARCHAR2(90) NOT NULL
           , PAYMENT_STATUS CHAR(1) DEFAULT 'Y' NOT NULL
           );
           

CREATE TABLE 
       BOARD 
           ( 
             BOARD_NO NUMBER CONSTRAINT PK_BOARD PRIMARY KEY
           , PLAYLIST_NO NUMBER CONSTRAINT FK_BOARD_PLAYLIST_NO REFERENCES PLAYLIST(PLAYLIST_NO) NOT NULL
           , MEMBER_NO NUMBER CONSTRAINT FK_BOARD_MEMBER_NO REFERENCES MEMBER(MEMBER_NO) NOT NULL
           , MUSIC_NO NUMBER CONSTRAINT FK_BOARD_MUSIC_NO REFERENCES MUSIC_FILE(MUSIC_NO) NOT NULL 
           , BOARD_TITLE VARCHAR2(90) NOT NULL
           , BOARD_CONTENT VARCHAR2(4000) NOT NULL
           , BOARD_COUNT NUMBER NULL
           , BOARD_ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL
           , BOARD_STATUS CHAR(1) DEFAULT 'Y' NOT NULL
           , BOARD_CATEGORY VARCHAR2(30) NOT NULL
           );

-- CREATE TABLE    인라인 방식 안먹음 
--BOARD_COMMENT
--           (
--             BOARD_COMMENT_NO NUMBER CONSTRAINT PK_BOARD_COMMENT_NO PRIMARY KEY
--          , BOARD_NO NUMBER CONSTRAINT FK_BOARD_COMMENT_NO REFERENCES BOARD_NO(BOARD_NO) NOT NULL
--           , MEMBER_NO NUMBER CONSTRAINT FK_BOARD_COMMENT_MEMBER_NO REFERENCES MEMBER(MEMBER_NO) NOT NULL
--           , COMMENT_CONTENT VARCHAR2(600)
--          , COMMENT_ENROLL_DATE DATE
--           );
--      
    CREATE TABLE 
   BOARD_COMMENT
                (
                  BOARD_COMMENT_NO NUMBER NOT NULL
                , BOARD_NO NUMBER NOT NULL
                , MEMBER_NO NUMBER NOT NULL
                , COMMENT_CONTENT VARCHAR2(600)
                , COMMENT_ENROLL_DATE DATE
                , CONSTRAINT PK_BOARD_COMMENT_NO PRIMARY KEY (BOARD_COMMENT_NO)
                , CONSTRAINT FK_BOARD_COMMENT_NO FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO)
                , CONSTRAINT FK_BOARD_COMMENT_MEMBER_NO FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

    
CREATE TABLE RECOMMEND_LIST
    (
      MEMBER_NO NUMBER NOT NULL
    , PLAYLIST_NO NUMBER NOT NULL 
    );

CREATE TABLE
        CART 
           (
             MEMBER_NO NUMBER CONSTRAINT PK_CART_MEMBER_NO PRIMARY KEY
           , MUSIC_NO NUMBER CONSTRAINT FK_CART_MUSIC_NO REFERENCES MUSIC_LIST(MUSIC_NO) NOT NULL
           , PLAYLIST_NO NUMBER CONSTRAINT FK_CART_PLAYLIST_NO REFERENCES PLAYLIST(PLAYLIST_NO) NOT NULL
           );
           
           
           
CREATE TABLE FRIEND_LIST
     (
       FRIEND_NO NUMBER PRIMARY KEY
     , MEMBER_NO NUMBER REFERENCES MEMBER NOT NULL
     , PLAYLIST_NO NUMBER REFERENCES PLAYLIST NOT NULL
     );

-- CREATE TABLE RECENT_MUSIC 이것도 인라인 안먹음
--      (
--        MEMBER_NO NUMBER REFERENCES MEMBER(MEMBER_NO) NOT NULL
--      ,  MUSIC_NO NUMBER REFERENCES MUSIC_FILE(MUSIC_NO) NOT NULL
--     );
     



CREATE TABLE PAYMENT_DETAIL
     (
       MEMBER_NO NUMBER REFERENCES MEMBER NOT NULL
     , SUBSCRIBE_STATUS CHAR(1) DEFAULT 'Y' NOT NULL
     , SUBSCRIBE_START_DATE DATE DEFAULT SYSDATE
     , SUBSCRIBE_END_DATE DATE 
     );

---------------------------------------------------------





           



     CREATE TABLE
  PLAYLIST_DETAIL
                (
                  PLAYLIST_NO NUMBER CONSTRAINT PK_PLAYLIST_DETAIL_NO PRIMARY KEY
                , PLAYLIST_MUSIC_TOTAL VARCHAR2(4000) NOT NULL 
                );
           
           
           --------
           

COMMENT ON COLUMN CART.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN CART.MUSIC_NO IS '음원번호';
COMMENT ON COLUMN CART.PLAYLIST_NO IS '플레이 리스트 번호';

COMMENT ON COLUMN PLAYLIST.PLAYLIST_NO IS '플레이 리스트 번호';
COMMENT ON COLUMN PLAYLIST.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN PLAYLIST.PLAYLIST_NAME IS '플레이 리스트 이름';
COMMENT ON COLUMN PLAYLIST.PAYMENT_STATUS IS '무료 회원 여부';
           

COMMENT ON COLUMN PLAYLIST_DETAIL.PLAYLIST_NO IS '플레이 리스트 번호';
COMMENT ON COLUMN PLAYLIST_DETAIL.PLAYLIST_MUSIC_TOTAL IS '플레이 리스트에 담는 음원들 총합 (최대 50곡)';


COMMENT ON COLUMN MUSIC_LIST.MUSIC_NO IS '음원 번호';
COMMENT ON COLUMN MUSIC_LIST.MUSIC_TITLE IS '음원 제목';
COMMENT ON COLUMN MUSIC_LIST.MUSIC_SINGER IS '음원의 가수';
COMMENT ON COLUMN MUSIC_LIST.MUSIC_COUNT IS '음원 조회수';
COMMENT ON COLUMN MUSIC_LIST.MUSIC_GENRE IS '음원 장르';
COMMENT ON COLUMN MUSIC_LIST.MUSIC_LIKE IS '음원 좋아요';
COMMENT ON COLUMN MUSIC_LIST.MUSIC_DISLIKE IS '음원 싫어요';
COMMENT ON COLUMN MUSIC_LIST.LYRICS IS '가사';
COMMENT ON COLUMN MUSIC_LIST.MUSIC_PUBLIC_STATUS IS '음원 공개 상태';


COMMENT ON COLUMN MUSIC_COMMENT.MUSIC_COMMENT_NO IS '음원 댓글 번호';
COMMENT ON COLUMN MUSIC_COMMENT.MUSIC_NO IS '음원 번호';
COMMENT ON COLUMN MUSIC_COMMENT.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN MUSIC_COMMENT.COMMENT IS '댓글 내용';
COMMENT ON COLUMN MUSIC_COMMENT.COMMENT_LIKE IS '댓글 좋아요';
COMMENT ON COLUMN MUSIC_COMMENT.COMMENT_DISLIKE IS '댓글 싫어요';
COMMENT ON COLUMN MUSIC_COMMENT.COMMENT_DATE IS '작성일자';

COMMENT ON COLUMN MUSIC_FILE.MUSIC_NO IS '음원 번호';
COMMENT ON COLUMN MUSIC_FILE.MUSIC_FILE_ORIGIN_NAME IS '음원파일 원본 이름';
COMMENT ON COLUMN MUSIC_FILE.MUSIC_FILE_EDIT_NAME IS '음원파일 수정 이름';
COMMENT ON COLUMN MUSIC_FILE.MUSIC_FILE_STORE_PATH IS '음원파일 저장 경로';
COMMENT ON COLUMN MUSIC_FILE.MUSIC_IMAGE_ORIGIN_NAME IS '음원이미지 원본이름';
COMMENT ON COLUMN MUSIC_FILE.MUSIC_IMAGE_EDIT_NAME IS '음원이미지 수정 이름';
COMMENT ON COLUMN MUSIC_FILE.MUSIC_IMAGE_PATH IS '음원이미지 파일 경로';


COMMENT ON COLUMN RECOMMEND_LIST.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN RECOMMEND_LIST.PLAYLIST_NO IS '플레이리스트 번호';



COMMENT ON COLUMN FRIEND_LIST.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN FRIEND_LIST.FRIEND_NO IS '친구 회원 번호';
COMMENT ON COLUMN FRIEND_LIST.PLAYLIST_NO IS '플레이리스트 번호';

COMMENT ON COLUMN RECENT_MUSIC.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN RECENT_MUSIC.MUSIC_NO IS '음원 번호';

COMMENT ON COLUMN PAYMENT_DETAIL.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN PAYMENT_DETAIL.SUBSCRIBE_STATUS IS '정기구독 상태';
COMMENT ON COLUMN PAYMENT_DETAIL.SUBSCRIBE_START_DATE IS '정기구독 시작 시각';
COMMENT ON COLUMN PAYMENT_DETAIL.SUBSCRIBE_END_DATE IS '정기구독 종료 시각';

COMMENT ON COLUMN BOARD_COMMENT.BOARD_COMMENT_NO IS '게시판 댓글 번호';
COMMENT ON COLUMN BOARD_COMMENT.BOARD_NO IS '게시판 번호';
COMMENT ON COLUMN BOARD_COMMENT.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN BOARD_COMMENT.COMMENT_CONTENT IS '댓글 내용';
COMMENT ON COLUMN BOARD_COMMENT.COMMENT_ENROLL_DATE IS '댓글 작성 일자';

COMMENT ON COLUMN CART.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN CART.MUSIC_NO IS '음원 번호';
COMMENT ON COLUMN CART.PLAYLIST_NO IS '플레이 리스트 번호';

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN BOARD.PLAYLIST_NO IS '플레이 리스트 번호';
COMMENT ON COLUMN BOARD.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN BOARD.MUSIC_NO IS '음원 번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.BOARD_COUNT IS '게시글 조회수';
COMMENT ON COLUMN BOARD.BOARD_ENROLL_DATE IS '게시글 작성명';
COMMENT ON COLUMN BOARD.BOARD_STATUS IS '게시글 상태';
COMMENT ON COLUMN BOARD.BOARD_CATEGORY IS '게시글 카테고리';

COMMENT ON COLUMN LOCATION.LOCATION_NO IS '지역 번호';
COMMENT ON COLUMN LOCATION.LOCATION_NAME IS '지역 이름';

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN MEMBER.LOCATION_NO IS '지역 번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '별칭';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.AGE IS '나이';
COMMENT ON COLUMN MEMBER.STATUS IS '가입 상태';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '가입 일자';
COMMENT ON COLUMN MEMBER.REPORT_COUNT IS '신고 누적 횟수';

